#include "ShaderPropertyMatrix.h"
#include "ShaderPropertyScalarBool.h"
#include "ShaderPropertyScalarFloat.h"
#include "ShaderPropertyScalarInt.h"
#include "ShaderPropertyVector.h"
#include "ShaderPropertyShaderResource.h"
#include "ShaderPropertyTexture2D.h"
#include "ShaderProperyConstantBuffer.h"